# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4238614d9e73d9c6546f8a9aed8f0408bf1e99079de11f15e71384bbe00d98697fa79c337eb3d3f03f3653150dfce15ff4b5d3a6e02b257f970534fd9816ddc9

test:
  secret_key_base: 0703608abfe3651ce90e072cd1aae7a74c04359a81df36f12be3365191aaf105096852f5e6f6260e1ab6e376970b42a0211356e1a9c95587dde728f8f7a92b04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
